### ISSUE TITLE
[Composition Root]

### ISSUE THREAD

**Issue by Migorithm** [Migorithm/ruva#75]
- [x]  Create Method on MessageBus called `create`  #69 
- [x]  Activator: create activator to get type path and initializer #67 
- [x] Make UOW object-safe #76
- [x] Make Repository object-safe #77
- [x] Change executor signature #78
- [x] Add generic for Outbox on `UnitOfWork` #80

**Comment by Migorithm** [comment]
Currently, object graphs are made on the framework, and accessible globally, indicating that it is not so much composer that should be invoked in composition root, specifically in executables, as service locator, common antipattern.

**Comment by Migorithm** [comment]
As it is done, the project version is promoted to 0.2.
